hostname wan1
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 10.255.0.41
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.255.10.1 remote-as 65000
 neighbor 10.255.0.0 remote-as 65110
 neighbor 10.255.0.4 remote-as 65210
 neighbor 10.255.1.0 remote-as 65301
 neighbor 10.255.1.4 remote-as 65302
 neighbor 10.255.1.8 remote-as 65303
 !
 address-family ipv4 unicast
  network 10.255.0.41/32
  redistribute connected
  neighbor 10.255.10.1 activate
  neighbor 10.255.0.0 activate
  neighbor 10.255.0.4 activate
  neighbor 10.255.1.0 activate
  neighbor 10.255.1.4 activate
  neighbor 10.255.1.8 activate
 exit-address-family
!
line vty
!
