hostname wan2
service integrated-vtysh-config
!
router bgp 65000
 bgp router-id 10.255.0.42
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor 10.255.10.0 remote-as 65000
 neighbor 10.255.0.2 remote-as 65110
 neighbor 10.255.0.6 remote-as 65210
 neighbor 10.255.1.2 remote-as 65301
 neighbor 10.255.1.6 remote-as 65302
 neighbor 10.255.1.10 remote-as 65303
 !
 address-family ipv4 unicast
  network 10.255.0.42/32
  redistribute connected
  neighbor 10.255.10.0 activate
  neighbor 10.255.0.2 activate
  neighbor 10.255.0.6 activate
  neighbor 10.255.1.2 activate
  neighbor 10.255.1.6 activate
  neighbor 10.255.1.10 activate
 exit-address-family
!
line vty
!
