---
acl:
  name: "GUEST-TO-DC"
  apply_interfaces:
    - "interface Ethernet3.20"
  lines:
    - "10 deny ip {{ guest_subnet }} 10.10.1.0/24"
    - "20 deny ip {{ guest_subnet }} 10.20.1.0/24"
    - "30 deny ip {{ guest_subnet }} 10.30.1.0/24"
    - "40 deny ip {{ guest_subnet }} 10.10.2.0/24"
    - "50 deny ip {{ guest_subnet }} 10.20.2.0/24"
    - "60 deny ip {{ guest_subnet }} 10.30.2.0/24"
    - "70 deny ip any any"
