---
acl:
  name: "GUEST-TO-DC"
  apply_interfaces:
    - "interface Ethernet3.20"
  lines:
    - "10 permit ip {{ guest_subnet }} 10.10.101.0/24"
    - "20 permit ip {{ guest_subnet }} 10.10.102.0/24"
    - "30 permit ip {{ guest_subnet }} 10.10.103.0/24"
    - "40 deny ip any any"
